[package]
name = "packed-display-buffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "fuzzer",
]

[dependencies]
embedded-graphics-core = "0.3.3"

[dev-dependencies]
rand = "0.8.5"
